name: quiby

networks:
  quiby_net:
    external: true

services:
  kafka:
    image: redpandadata/redpanda:v25.2.1
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:9092
    networks: [quiby_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers kafka:9092 >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
